#pragma once
#include <sdk/te_types.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declaration */
struct cJSON;

/**
 * Event types generated by the 7 event sources in the TaskbarEngine.
 * Plugins subscribe to these via PluginContext.subscribe().
 */
typedef enum TE_EventType {
    TE_EVENT_NONE = 0,
    TE_EVENT_CONFIG_CHANGED,    /**< Config file hot-reloaded; payload: TE_ConfigChangedData */
    TE_EVENT_DPI_CHANGED,       /**< Monitor DPI changed; payload: TE_DpiChangedData */
    TE_EVENT_DISPLAY_CHANGED,   /**< Display resolution/layout changed; payload: TE_DisplayChangedData */
    TE_EVENT_TASKBAR_GEOMETRY,  /**< Taskbar size/position changed; payload: TE_TaskbarGeometryData */
    TE_EVENT_TASKBAR_MOUSE,     /**< Mouse moved over taskbar; payload: TE_TaskbarMouseData */
    TE_EVENT_SHELL_HOOK,        /**< Shell hook (app open/close/focus); payload: TE_ShellHookData */
    TE_EVENT_POWER,             /**< Power event (suspend/resume); payload: TE_PowerData */
    TE_EVENT_DEVICE,            /**< Device change (monitor plug/unplug); payload: TE_DeviceData */
    TE_EVENT_VDESKTOP,          /**< Virtual desktop switch; payload: NULL */
    TE_EVENT_COUNT              /**< Sentinel: total number of event types */
} TE_EventType;

typedef struct TE_ConfigChangedData {
    const char* plugin_name;          /**< Name of the plugin whose config section changed */
    const struct cJSON* new_config;   /**< Pointer to the new config sub-tree for this plugin */
} TE_ConfigChangedData;

typedef struct TE_DpiChangedData {
    uint32_t old_dpi;
    uint32_t new_dpi;
    HWND hwnd;
} TE_DpiChangedData;

typedef struct TE_DisplayChangedData {
    uint32_t width;
    uint32_t height;
    uint32_t bits_per_pixel;
} TE_DisplayChangedData;

typedef struct TE_TaskbarGeometryData {
    RECT new_rect;
    HMONITOR monitor;
} TE_TaskbarGeometryData;

typedef struct TE_TaskbarMouseData {
    POINT cursor_pos;
    BOOL is_in_taskbar;
} TE_TaskbarMouseData;

typedef struct TE_ShellHookData {
    int shell_msg;    /**< HSHELL_* message code */
    HWND target_hwnd; /**< Window that triggered the shell hook */
} TE_ShellHookData;

typedef struct TE_PowerData {
    BOOL is_suspending;   /**< TRUE if entering suspend, FALSE if resuming */
} TE_PowerData;

typedef struct TE_DeviceData {
    BOOL is_arrival;      /**< TRUE if device arrived, FALSE if removed */
} TE_DeviceData;

#ifdef __cplusplus
}
#endif
